apiVersion: skaffold/v2beta19
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
      - ./infra/k8s-dev/*
build:
  local:
    push: false
  artifacts:
    - image: spacecoupe/auth
      context: auth
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: spacecoupe/tickets
      context: tickets
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: spacecoupe/orders
      context: orders
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: spacecoupe/expiration
      context: expiration
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: spacecoupe/payment
      context: payment
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: spacecoupe/client
      context: client
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
